---
apiVersion: v2
name: tra-nifi
version: 1.3.1
appVersion: 2.0.2-M2
description: Apache NiFi is a software project from the Apache Software Foundation designed to automate the flow of data between software systems.
keywords:
  - nifi
  - data
  - process
home: https://nifi.apache.org/
icon: https://svn.apache.org/repos/asf/nifi/site/trunk/images/niFi-logo-horizontal-scaled.png
source:
  - https://github.com/cetic/helm-nifi
maintainers:
  - name: aturley
    email: agturley@gmail.com
dependencies:
  - name: zookeeper
    version: 9.2.7
    condition: zookeeper.enabled
  - name: nifi-registry
    alias: registry
    version: 1.0.0
    condition: registry.enabled
  - name: ca
    version: 1.0.1
    condition: ca.enabled
  - name: openldap
    version: ~1.2.4
    condition: openldap.enabled
