{{- if .Values.auth.singleUser.generateSecret }}
{{- $secretName := printf "%s-single-user-credentials" (include "apache-nifi.fullname" .) }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName }}
{{- $username := "" }}
{{- $password := "" }}
{{- if $existing }}
  {{- $username = index $existing.data "username" | b64dec }}
  {{- $password = index $existing.data "password" | b64dec }}
{{- else }}
  {{- $username = default (randAlphaNum 16) .Values.auth.singleUser.username }}
  {{- $password = randAlphaNum 32 }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nifi.commonLabels" . | nindent 4 }}
    app: {{ include "apache-nifi.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  username: {{ $username | b64enc }}
  password: {{ $password | b64enc }}
{{- end }}
